# Generated by Django 4.0 on 2021-12-28 23:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_alter_usuario_avatar_delete_dependencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=250)),
                ('abreviatura', models.CharField(max_length=25)),
                ('modi_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('modi_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_modi_por', to='home.usuario')),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_titular', to='home.usuario')),
            ],
            options={
                'ordering': ['dependencia'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=250)),
                ('abreviatura', models.CharField(max_length=25)),
                ('modi_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('modi_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medida_modi_por', to='home.usuario')),
            ],
            options={
                'ordering': ['unidad'],
            },
        ),
        migrations.CreateModel(
            name='Subdireccione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdireccion', models.CharField(max_length=250)),
                ('titutlar', models.CharField(max_length=250)),
                ('cargo', models.CharField(max_length=250)),
                ('modi_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdir_dependencia', to='proyecto.dependencia')),
                ('modi_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdir_modi_por', to='home.usuario')),
            ],
            options={
                'ordering': ['subdireccion'],
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('fecha_oficio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('asunto', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('uea', models.BooleanField(blank=True, default=False, null=True)),
                ('seif', models.BooleanField(blank=True, default=False, null=True)),
                ('se', models.BooleanField(blank=True, default=False, null=True)),
                ('sad', models.BooleanField(blank=True, default=False, null=True)),
                ('snpi', models.BooleanField(blank=True, default=False, null=True)),
                ('sfo', models.BooleanField(blank=True, default=False, null=True)),
                ('st', models.BooleanField(blank=True, default=False, null=True)),
                ('sai', models.BooleanField(blank=True, default=False, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='oficios/2021/12/28/')),
                ('archivo_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('creado_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('modi_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_creado_por', to='home.usuario')),
                ('modi_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_modi_por', to='home.usuario')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('Puede Crear', 'Puede Editar'),),
            },
        ),
    ]
