# Generated by Django 4.0 on 2021-12-29 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usuario_avatar_delete_dependencia'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='sad',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='sai',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='se',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='seif',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='sfo',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='snpi',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='st',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='uea',
        ),
        migrations.AddField(
            model_name='oficio',
            name='anno',
            field=models.IntegerField(blank=True, default=2021, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='consecutivo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='dir_remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_dir_remitente_dep', to='proyecto.dependencia'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='instrucciones',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='recibe',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='remitente',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='tipo_documento',
            field=models.CharField(blank=True, default='O', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='OficioConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('fecha_oficio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('asunto', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('uea', models.BooleanField(blank=True, default=False, null=True)),
                ('seif', models.BooleanField(blank=True, default=False, null=True)),
                ('se', models.BooleanField(blank=True, default=False, null=True)),
                ('sad', models.BooleanField(blank=True, default=False, null=True)),
                ('snpi', models.BooleanField(blank=True, default=False, null=True)),
                ('sfo', models.BooleanField(blank=True, default=False, null=True)),
                ('st', models.BooleanField(blank=True, default=False, null=True)),
                ('sai', models.BooleanField(blank=True, default=False, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='oficios_consulta/2021/12/28/')),
                ('archivo_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('creado_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('modi_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficon_creado_por', to='home.usuario')),
                ('modi_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficon_modi_por', to='home.usuario')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('Puede Crear', 'Puede Editar'),),
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(blank=True, default=2021, null=True)),
                ('fecha_evento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hora_evento', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('asunto', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('lugar', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('seguimiento', models.TextField(blank=True, default='', max_length=4000, null=True)),
                ('respuesta', models.TextField(blank=True, default='', max_length=4000, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='eventos/2021/12/28/')),
                ('archivo_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('creado_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('modi_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_creado_por', to='home.usuario')),
                ('dependencia_solicita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_solicita_dep', to='proyecto.dependencia')),
                ('modi_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_modi_por', to='home.usuario')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (('Puede Crear', 'Puede Editar'),),
            },
        ),
    ]
