# Generated by Django 4.0 on 2022-06-22 20:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_oficio_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='creado_el',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 25, 15, 21, 57, 717979), null=True),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='modi_el',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
