# Generated by Django 4.0 on 2021-12-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usuario_avatar_delete_dependencia'),
        ('proyecto', '0003_alter_evento_archivo_alter_oficio_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='modi_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medida_modi_por', to='home.usuario'),
        ),
        migrations.DeleteModel(
            name='OficioConsulta',
        ),
    ]
