# Generated by Django 4.0 on 2021-12-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usuario_avatar_delete_dependencia'),
        ('proyecto', '0004_alter_unidadmedida_modi_por_delete_oficioconsulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='modi_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_modi_por', to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_creado_por', to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='modi_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_modi_por', to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_creado_por', to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='modi_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_modi_por', to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='subdireccione',
            name='modi_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdir_modi_por', to='home.usuario'),
        ),
    ]
