# Generated by Django 4.0 on 2021-12-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_dependencia_modi_por_alter_evento_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='tipo_documento',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Firmado'), (1, 'Remitente')], default=1, null=True),
        ),
    ]
