# Generated by Django 4.0 on 2022-01-05 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_alter_evento_archivo_alter_oficio_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oficio',
            old_name='fecha_oficio',
            new_name='fecha_captura',
        ),
        migrations.AddField(
            model_name='oficio',
            name='fecha_documento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='anno',
            field=models.IntegerField(blank=True, default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/2022/1/4/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='anno',
            field=models.IntegerField(blank=True, default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/1/4/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='tipo_documento',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'RECIBIDO'), (1, 'FIRMADO POR EL(LA) DIRECTOR(A)')], default=1, null=True),
        ),
    ]
