# Generated by Django 4.0 on 2022-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_alter_evento_archivo_alter_oficio_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='subdireccion_id',
            field=models.ManyToManyField(to='proyecto.Subdireccione'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/2022/1/15/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/1/15/'),
        ),
    ]
