# Generated by Django 4.0 on 2022-01-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_oficio_subdireccion_id_alter_evento_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdireccione',
            name='abreviatura',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
