# Generated by Django 4.0 on 2022-01-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_subdireccione_abreviatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencia',
            options={'ordering': ['dependencia'], 'verbose_name': 'Dependencia', 'verbose_name_plural': 'Dependencias'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['pk'], 'permissions': (('Puede Crear', 'Puede Editar'),), 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='oficio',
            options={'ordering': ['pk'], 'permissions': (('Puede Crear', 'Puede Editar'),), 'verbose_name': 'Oficio', 'verbose_name_plural': 'Oficios'},
        ),
        migrations.AlterModelOptions(
            name='subdireccione',
            options={'ordering': ['subdireccion'], 'verbose_name': 'Subdirección', 'verbose_name_plural': 'Subdirecciones'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ['unidad'], 'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.RenameField(
            model_name='oficio',
            old_name='subdireccion_id',
            new_name='subdireccion',
        ),
    ]
