# Generated by Django 4.0 on 2022-01-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_alter_dependencia_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficio',
            options={'ordering': ['pk'], 'permissions': (['Puede Crear', 'Puede Editar'],), 'verbose_name': 'Oficio', 'verbose_name_plural': 'Oficios'},
        ),
    ]
