# Generated by Django 4.0 on 2022-01-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_alter_oficio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficio',
            options={'ordering': ['pk'], 'verbose_name': 'Oficio', 'verbose_name_plural': 'Oficios'},
        ),
    ]
