# Generated by Django 4.0 on 2023-08-24 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_alter_oficio_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 27, 12, 32, 58, 555765), null=True),
        ),
    ]
