# Generated by Django 4.0 on 2022-02-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_alter_evento_archivo_alter_oficio_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/2022/2/23/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/2/23/'),
        ),
    ]
