# Generated by Django 4.0 on 2022-02-23 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_alter_evento_archivo_alter_oficio_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdireccione',
            old_name='titutlar',
            new_name='titular',
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 25, 14, 8, 56, 315208), null=True),
        ),
    ]
