# Generated by Django 5.1.2 on 2024-10-11 16:58

import datetime
import siad.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_alter_oficio_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='anno',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/2024/10/11/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='anno',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2024/10/11/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 14, 10, 58, 56, 118026), null=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios_respuestas/2024/10/11/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
    ]
