# Generated by Django 4.0 on 2022-02-24 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_alter_oficio_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/2022/2/24/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/2/24/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=None, default=datetime.datetime(2022, 2, 26, 13, 11, 17, 94369), null=None),
        ),
    ]
