# Generated by Django 4.0 on 2022-02-25 00:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_alter_evento_archivo_alter_oficio_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='creado_el',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 26, 18, 38, 4, 888719), null=True),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='modi_el',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
