# Generated by Django 4.0 on 2022-02-25 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0021_alter_oficio_creado_el_alter_oficio_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(default=datetime.datetime(2022, 2, 27, 19, 47, 58, 876204), null=None),
        ),
    ]
