# Generated by Django 4.0 on 2022-03-11 23:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_usuario_options'),
        ('proyecto', '0025_oficio_fecha_recibido_alter_evento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/2022/3/11/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/3/11/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 14, 17, 48, 21, 901829), null=True),
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='respuesta_oficio/2022/3/11/')),
                ('archivo_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('creado_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('modi_el', models.DateField(blank=True, null=True, verbose_name='died')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuesta_creado_por', to='home.usuario')),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuesta_modi_por', to='home.usuario')),
                ('oficios', models.ManyToManyField(to='proyecto.Oficio')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuesta',
                'ordering': ['pk'],
                'permissions': (('Puede Crear', 'Puede Editar'),),
            },
        ),
    ]
