# Generated by Django 4.0 on 2022-03-12 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0026_alter_evento_archivo_alter_oficio_archivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestas',
            options={'ordering': ['pk'], 'permissions': (('Puede Crear', 'Puede Editar'),), 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='oficios',
        ),
        migrations.AddField(
            model_name='oficio',
            name='respuestas',
            field=models.ManyToManyField(to='proyecto.Respuestas'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 14, 18, 31, 6, 725687), null=True),
        ),
    ]
