# Generated by Django 4.0 on 2022-03-15 22:32

import datetime
from django.db import migrations, models
import siad.functions


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0027_alter_respuestas_options_remove_respuestas_oficios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestas',
            options={'ordering': ['-pk'], 'permissions': (('Puede Crear', 'Puede Editar'),), 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/2022/3/15/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/3/15/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 18, 16, 32, 26, 434022), null=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='respuesta_oficio/2022/3/15/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='respuesta',
            field=models.CharField(default='', max_length=500),
        ),
    ]
