# Generated by Django 4.0 on 2022-03-15 22:34

import datetime
from django.db import migrations, models
import siad.functions


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0028_alter_respuestas_options_alter_evento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 18, 16, 34, 51, 656668), null=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/3/15/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
    ]
