# Generated by Django 4.0 on 2022-03-16 19:21

import datetime
from django.db import migrations, models
import siad.functions


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0029_alter_oficio_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='estatus',
            field=models.SmallIntegerField(choices=[(0, 'RECIBIDO'), (1, 'EN PROCESO'), (2, 'TURNADO A OTRA DEPENDENCIA'), (3, 'NO PROCEDE'), (4, 'RESUELTO FAVORABLE'), (5, 'RESUELTO NO FAVORABLE')], default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='eventos/2022/3/16/'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/3/16/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 19, 13, 21, 57, 729715), null=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios_respuestas/2022/3/16/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
    ]
