# Generated by Django 4.0 on 2022-03-16 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0030_respuestas_estatus_alter_evento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 19, 14, 3, 18, 110056), null=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='respuesta',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
