# Generated by Django 4.0 on 2022-05-19 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0032_subdireccione_is_visible_alter_evento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='fecha_respuesta',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 22, 15, 7, 20, 214142), null=True),
        ),
    ]
