# Generated by Django 4.0 on 2022-07-16 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import siad.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0012_alter_evento_archivo_alter_oficio_archivo_and_more'),
        ('home', '0009_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioEnviadoRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(default='', max_length=2000)),
                ('fecha_respuesta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estatus', models.SmallIntegerField(choices=[(0, 'RECIBIDO'), (1, 'EN PROCESO'), (2, 'TURNADO A OTRA DEPENDENCIA'), (3, 'NO PROCEDE'), (4, 'RESUELTO FAVORABLE'), (5, 'RESUELTO NO FAVORABLE')], default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='oficiosenviados_respuestas/2022/7/16/', validators=[siad.functions.validate_file_extension, siad.functions.file_size])),
                ('archivo_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('creado_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_env_resp_creado_por', to='home.usuario')),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_env_resp_modi_por', to='home.usuario')),
            ],
            options={
                'verbose_name': 'Oficio Enviado Respuesta',
                'verbose_name_plural': 'Oficios Enviados Respuestas',
                'ordering': ['-pk'],
                'permissions': (('Puede Crear', 'Puede Editar'),),
            },
        ),
        migrations.CreateModel(
            name='OficioEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(blank=True, default=2022, null=True)),
                ('consecutivo', models.IntegerField(blank=True, default=0, null=True)),
                ('oficio', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('fecha_oficio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('asunto', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('instrucciones', models.TextField(blank=True, default='', max_length=4000, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='oficios/2022/7/16/', validators=[siad.functions.validate_file_extension, siad.functions.file_size])),
                ('archivo_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('creado_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_env_creado_por', to='home.usuario')),
                ('destinatarios', models.ManyToManyField(to='proyecto.Dependencia')),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_env_modi_por', to='home.usuario')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_enviado_remitente_dep', to='proyecto.subdireccione')),
                ('respuestas', models.ManyToManyField(to='oficiosenviados.OficioEnviadoRespuestas')),
                ('unidad_administrativa', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ua_ofi_env_unidad_administrativa', to='proyecto.unidadadministrativa')),
            ],
            options={
                'verbose_name': 'Oficio Enviado',
                'verbose_name_plural': 'Oficios Enviados',
                'ordering': ['pk'],
            },
        ),
    ]
