# Generated by Django 4.0 on 2022-07-05 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import siad.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0009_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(blank=True, default=2022, null=True)),
                ('consecutivo', models.IntegerField(blank=True, default=0, null=True)),
                ('oficio', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('remitente', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('del_remitente', models.CharField(default='', max_length=250)),
                ('asunto', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('instrucciones', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('fecha_documento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_captura', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_recibido', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='oficios/2022/7/5/', validators=[siad.functions.validate_file_extension, siad.functions.file_size])),
                ('archivo_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('creado_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_env_creado_por', to='home.usuario')),
                ('dir_remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_enviado_dir_remitente_dep', to='proyecto.subdireccione')),
                ('modi_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_env_modi_por', to='home.usuario')),
                ('recibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficioenviado_recibe_dep', to='proyecto.dependencia')),
                ('respuestas', models.ManyToManyField(to='proyecto.Respuestas')),
                ('subdireccion', models.ManyToManyField(to='proyecto.Subdireccione')),
                ('unidad_administrativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ua_ofi_env_unidad_administrativa', to='proyecto.unidadadministrativa')),
            ],
            options={
                'verbose_name': 'Oficio Enviado',
                'verbose_name_plural': 'Oficios Enviados',
                'ordering': ['pk'],
            },
        ),
    ]
