# Generated by Django 4.0 on 2022-07-07 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import siad.functions


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('oficiosenviados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioEnviadoRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(default='', max_length=2000)),
                ('fecha_respuesta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estatus', models.SmallIntegerField(choices=[(0, 'RECIBIDO'), (1, 'EN PROCESO'), (2, 'TURNADO A OTRA DEPENDENCIA'), (3, 'NO PROCEDE'), (4, 'RESUELTO FAVORABLE'), (5, 'RESUELTO NO FAVORABLE')], default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='oficiosenviados_respuestas/2022/7/7/', validators=[siad.functions.validate_file_extension, siad.functions.file_size])),
                ('archivo_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('creado_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modi_el', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Oficio Enviado Respuesta',
                'verbose_name_plural': 'Oficios Enviados Respuestas',
                'ordering': ['-pk'],
                'permissions': (('Puede Crear', 'Puede Editar'),),
            },
        ),
        migrations.RenameField(
            model_name='oficioenviado',
            old_name='fecha_captura',
            new_name='fecha_oficio',
        ),
        migrations.RemoveField(
            model_name='oficioenviado',
            name='del_remitente',
        ),
        migrations.RemoveField(
            model_name='oficioenviado',
            name='dir_remitente',
        ),
        migrations.RemoveField(
            model_name='oficioenviado',
            name='fecha_documento',
        ),
        migrations.RemoveField(
            model_name='oficioenviado',
            name='fecha_recibido',
        ),
        migrations.RemoveField(
            model_name='oficioenviado',
            name='recibe',
        ),
        migrations.RemoveField(
            model_name='oficioenviado',
            name='subdireccion',
        ),
        migrations.AddField(
            model_name='oficioenviado',
            name='destinatarios',
            field=models.ManyToManyField(to='proyecto.Dependencia'),
        ),
        migrations.AlterField(
            model_name='oficioenviado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2022/7/7/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
        migrations.AlterField(
            model_name='oficioenviado',
            name='instrucciones',
            field=models.TextField(blank=True, default='', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='oficioenviado',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_enviado_remitente_dep', to='proyecto.subdireccione'),
        ),
    ]
