# Generated by Django 4.0 on 2022-07-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficiosenviados', '0002_remove_oficioenviado_subdireccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oficioenviado',
            old_name='recibe',
            new_name='dependencias',
        ),
        migrations.RemoveField(
            model_name='oficioenviado',
            name='del_remitente',
        ),
        migrations.RemoveField(
            model_name='oficioenviado',
            name='remitente',
        ),
    ]
