# Generated by Django 4.0 on 2022-07-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_usuario_options'),
        ('oficiosenviados', '0002_oficioenviadorespuestas_and_more'),
        ('proyecto', '0002_alter_evento_archivo_alter_oficio_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficioenviado',
            name='unidad_administrativa',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ua_ofi_env_unidad_administrativa', to='proyecto.unidadadministrativa'),
        ),
        migrations.AddField(
            model_name='oficioenviadorespuestas',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_env_resp_creado_por', to='home.usuario'),
        ),
        migrations.AddField(
            model_name='oficioenviadorespuestas',
            name='modi_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofi_env_resp_modi_por', to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='oficioenviado',
            name='respuestas',
            field=models.ManyToManyField(to='oficiosenviados.OficioEnviadoRespuestas'),
        ),
    ]
