# Generated by Django 4.0 on 2023-08-24 18:22

from django.db import migrations, models
import siad.functions


class Migration(migrations.Migration):

    dependencies = [
        ('oficiosenviados', '0002_alter_oficioenviado_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficioenviado',
            name='anno',
            field=models.IntegerField(blank=True, default=2023, null=True),
        ),
        migrations.AlterField(
            model_name='oficioenviado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2023/8/24/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
        migrations.AlterField(
            model_name='oficioenviadorespuestas',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficiosenviados_respuestas/2023/8/24/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
    ]
