# Generated by Django 5.1.2 on 2024-10-11 16:58

import siad.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiosenviados', '0003_alter_oficioenviado_anno_alter_oficioenviado_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficioenviado',
            name='anno',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='oficioenviado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficios/2024/10/11/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
        migrations.AlterField(
            model_name='oficioenviadorespuestas',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='oficiosenviados_respuestas/2024/10/11/', validators=[siad.functions.validate_file_extension, siad.functions.file_size]),
        ),
    ]
