# Generated by Django 4.0 on 2022-07-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_oficio_fecha_respuesta'),
        ('oficiosenviados', '0003_rename_recibe_oficioenviado_dependencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficioenviado',
            name='dir_remitente',
        ),
        migrations.AddField(
            model_name='oficioenviado',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficio_enviado_remitente_dep', to='proyecto.subdireccione'),
        ),
    ]
