# Generated by Django 4.0 on 2021-12-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='uploadedFile',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='dateTimeOfUpload',
            new_name='avatar_datetime',
        ),
    ]
