# Generated by Django 4.0 on 2021-12-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_uploadedfile_usuario_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
