# Generated by Django 4.0 on 2022-01-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usuario_avatar_delete_dependencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['pk'], 'permissions': (['Puede Crear', 'Puede Editar'],)},
        ),
    ]
