# Generated by Django 4.0 on 2022-01-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['pk'], 'permissions': (('crear_usuario', 'crear_usuario'), ('editar_usuario', 'editar_usuario'))},
        ),
    ]
