# Generated by Django 4.0 on 2022-05-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['ap_paterno', 'ap_materno', 'nombre'], 'permissions': (('Crear Usuario', 'Crear Usuario'), ('Editar Usuario', 'Editar Usuario'))},
        ),
    ]
